import 'package:flutter/material.dart';

class AppLanguage {
  static final ValueNotifier<Locale> currentLocale = ValueNotifier(const Locale('pt'));

  static final Map<String, Map<String, String>> _localizedValues = {
    'pt': {
      'welcome': 'Olá, seja bem-vindo(a)! 👋',
      'myTrees': 'Suas Árvores',
      'seeAll': 'Ver todas',
      'adoptTree': 'Adotar uma Árvore',
      'reforestation': 'Reflorestamento local',
      'nativeSpecies': 'Espécies nativas do Vale do Sapucaí',
      'ranking': 'posição no ranking',
      'treesAdopted': 'Árvores adotadas',
      'atlanticForest': 'Mata Atlântica',
      'forest': 'Floresta',
      'map': 'Mapa',
      'incentives': 'Incentivos',
      'settings': 'Configurações',
      'loginTitle': 'Bem-vindo ao EcoMind 🌱',
      'emailOrUser': 'Email ou usuário',
      'password': 'Senha',
      'createNewAccount': 'Criar conta nova',
      'enter': 'Entrar',
      'defaultEcoUser': 'Usuário EcoMind',
      'defaultUser': 'Usuário',
      'monthsPlanted': 'meses plantada',
      'endangeredTag': '🔴 Ameaçada',
      'perMonth': '/mês',
      'adoptedStatus': '✓ Adotada!',
      'adoptAction': 'Adotar',

      // Services
      'errGetUser': 'Erro ao obter o usuário cadastrado.',
      'errSaveProfile': 'Conta criada no Auth, mas falhou ao salvar dados do perfil. Tente novamente.',
      'errUserNotFound': 'Nome de usuário não encontrado.',
      'errNoEmailAssociated': 'Nenhum e-mail associado a este nome de usuário.',
      'errInvalidCredentials': 'E-mail, usuário ou senha incorretos.',
      'errInvalidCredentialsDetail': 'E-mail ou senha incorretos. Verifique suas credenciais.',
      'errEmailNotFound': 'Nenhum usuário encontrado para este e-mail.',
      'errWrongPassword': 'Senha incorreta. Tente novamente.',
      'errEmailInUse': 'Este e-mail já está em uso por outra conta.',
      'errInvalidEmail': 'O e-mail digitado é inválido.',
      'errWeakPassword': 'A senha deve ter pelo menos 6 caracteres.',
      'errUserDisabled': 'Esta conta de usuário foi desativada.',
      'errTooManyRequests': 'Muitas tentativas malsucedidas. Tente novamente mais tarde.',
      'errNetworkFailed': 'Falha na conexão de rede. Verifique sua internet.',

      // Leaderboard / Ranking
      'rankingTitle': 'Ranking 🌿',
      'noRankingData': 'Nenhum dado de ranking encontrado.',
      'anonymous': 'Anônimo',
      'treesCountLabel': 'árvores',

      // Map / Mapa
      'mapTitle': 'Mapa de Reflorestamento 🗺️',
      'mapLoadError': 'Erro ao carregar o mapa:',
      'mapLocationHeader': 'Santa Rita do Sapucaí - MG',
      'mapTreesMapped': 'árvores mapeadas',
      'mapYourTreesCount': 'suas',
      'legendMyTrees': 'Suas árvores ⭐',
      'legendCommunity': 'Comunidade 🌳',
      'yourTreeBadge': 'Sua Árvore',
      'biomeLabel': 'Bioma',
      'locationLabel': 'Local',
      'removeTreeBtn': 'Remover Árvore',
      'treeRemovedSuccess': 'foi removida com sucesso!',
      'treeRemoveError': 'Erro ao remover árvore:',

      // Profile / Perfil
      'myProfileTitle': 'Meu Perfil',
      'memberSince': 'Membro desde Agosto, 2026',
      'accountControl': 'Controle da Conta',
      'changeUsername': 'Alterar nome de usuário',
      'changePassword': 'Alterar senha',
      'logout': 'Sair da conta',
      'deleteAccount': 'Deletar conta',
      'deleteAccountTitle': 'Excluir Conta?',
      'deleteAccountWarning': 'Esta ação é irreversível e apagará todos os seus dados e árvores adotadas.',
      'deleteAccountPinPrompt': 'Para confirmar, digite o código abaixo:',
      'cancel': 'Cancelar',
      'deletePermanently': 'Excluir Definitivamente',
      'reauthRequired': 'Por segurança, faça login novamente antes de excluir a conta.',
      'deleteAccountError': 'Erro ao apagar conta:',
      'unexpectedError': 'Erro inesperado:',

      // Settings / Configurações
      'settingsGeneral': 'Geral',
      'languageOption': 'Idioma',
      'notificationsOption': 'Notificações',
      'settingsSecuritySupport': 'Segurança & Suporte',
      'privacyOption': 'Privacidade',
      'helpSupportOption': 'Ajuda e Suporte',

      // Home Screen Extras
      'defaultExplorer': 'Explorador',
      'regionTag': '🌱 EcoMind · Sul de Minas',
      'welcomeHome': 'Olá, seja bem-vindo(a)! 👋',
      'bocainaCaptionWeb': 'Serra da Bocaina, na divisa dos estados de São Paulo e Rio de Janeiro',
      'bocainaCaptionMobile': 'Serra da Bocaina, na divisa dos estados de SP e RJ',
      'atlanticForestTitle': 'Mata Atlântica',
      'atlanticForestBody': 'A Mata Atlântica é o principal bioma da costa leste do Brasil, abrangendo principalmente os estados da região Sudeste e Sul. É aqui que ficam as bacias dos principais rios brasileiros, e uma biodiversidade gigantesca, com milhares de espécies. No estado de Minas Gerais, estão abrigados 70% dos mamíferos de todo o bioma, além de diversos tipos de vegetação. \n\nInfelizmente, a Mata Atlântica também é um dos biomas mais ameaçados do país, sendo que resta apenas 15,3% de toda sua cobertura original no território nacional. Em Minas, a situação é ainda mais crítica, com apenas 7% da cobertura original preservada. Os principais pontos de reservas são o Vale do Rio Doce, Vale do Jequitinhonha, e a região sul do estado, próxima à Serra da Mantiqueira. \n\nNos anos de 2021 e 2022, Minas foi o estado que mais desmatou árvores do bioma. Em um mundo cada vez mais ameaçado pelas mudanças climáticas (como o El Niño que irá atingir recordes históricos nos próximos meses), é essencial que o ecossistema seja preservado e reflorestado.',
      'learnMoreAtlanticForest': 'Saiba mais sobre a Mata Atlântica',
      'sourcesAtlanticForest': 'Fontes: SOS Mata Atlântica, IBGE, Reserva da Biosfera da Mata Atlântica, G1',
      'loginToSeeTrees': 'Faça login para ver suas árvores.',
      'errLoadTrees': 'Erro ao carregar árvores:',
      'noTreesFound': 'Nenhuma árvore encontrada para esta conta.\nClique no círculo 🌱 abaixo para cadastrar a primeira!',

      // Incentives Screen
      'incentiveA': 'Benefício A',
      'incentiveB': 'Benefício B',
      'incentiveC': 'Benefício C',
      'incentiveD': 'Benefício D',
      'partnerMunSantaRita': 'Prefeitura Municipal de Santa Rita do Sapucaí',
      'partnerGovMinas': 'Governo do Estado de Minas Gerais',
      'partnerGovFederal': 'Governo Federal',
      'categoryFiscal': 'Benefício Fiscal',
      'noDescriptionYet': 'Ainda não há uma descrição.',
      'allFilter': 'Todos',
      'taxesFilter': '📜 Impostos',
      'incentivesAndRewards': 'Incentivos e Recompensas',
      'incentivesSubtitle': 'Adote árvores e libere benefícios exclusivos',
      'unlockedStatus': 'Liberado 🎉',
      'goalReached': 'Objetivo alcançado!',
      'treesProgressLabel': 'de',

      // Account Screen / Criar Conta
      'createAccountTitle': 'Criar Nova Conta 🌱',
      'usernameHint': 'Nome de usuário',
      'emailHint': 'Email',
      'passwordHint': 'Senha',
      'confirmPasswordHint': 'Confirmar senha',
      'registerBtn': 'Cadastrar',
      'accountCreatedSuccess': 'Conta criada com sucesso! 🌱',
      'errEmptyUser': 'Por favor, insira um nome de usuário.',
      'errEmptyEmail': 'Por favor, insira um email.',
      'errInvalidEmailFormat': 'Insira um email válido.',
      'errEmptyPassword': 'Por favor, insira uma senha.',
      'errPasswordTooShort': 'A senha deve ter pelo menos 6 caracteres.',
      'errEmptyConfirmPassword': 'Por favor, confirme sua senha.',
      'errPasswordsDoNotMatch': 'As senhas não coincidem.',

      // Adopt Screen / Adotar Árvores
      'adoptTreeTitle': 'Adotar Árvore',
      'adoptSubtitle': 'Espécies nativas do Vale do Sapucaí · Sul de Minas',
      'confirmAdoptionTitle': 'Confirmar Adoção 🌿',
      'speciesLabel': 'Espécie',
      'monthlyPriceLabel': 'Valor mensal: R\$',
      'paymentMethodLabel': 'Forma de Pagamento:',
      'pixPayment': 'PIX (Aprovação Instantânea)',
      'cardPayment': 'Cartão de Crédito Simulado',
      'payAndAdoptBtn': 'Pagar e Adotar',
      'loginRequiredToAdopt': '⚠️ Você precisa estar logado para adotar uma árvore.',
      'adoptionSuccessMsg': '🌱 Pagamento confirmado! {treeName} foi adotada com sucesso.',
      'adoptionErrorMsg': 'Erro ao processar adoção. Tente novamente.',
      'locationValeSapucai': 'Vale do Sapucaí · MG',

      // Filtros de Adotar Árvores
      'filterAll': 'Todas',
      'filterEndangered': '🔴 Ameaçadas',
      'filterRiparianForest': '🏞️ Mata ciliar',
      'filterFlowering': '🌼 Floração',
      'filterAttractsBirds': '🐦 Atrai aves',
      'filterFeedsFauna': '🐆 Alimenta a fauna',
      'filterLargeSize': '🌳 Grande porte',
      'filterRecoversSoil': '🌱 Recupera o solo',
      'filterWindDispersal': '💨 Dispersão pelo vento',
      'filterNitrogenFixation': '🍃 Fixação de nitrogênio',
      'filterEdibleNuts': '🌰 Castanhas comestíveis',
      'filterEdibleFruits': '🥭 Frutos comestíveis',

      // Biomas e Locais
      'biomeAtlanticForest': 'Mata Atlântica',

      // Espécies e Nomes de Árvores
      'treeIpeAmarelo': 'Ipê Amarelo',
      'treeJacaranda': 'Jacarandá',
      'treeCedroRosa': 'Cedro-rosa',
      'treeJequitibaRosa': 'Jequitibá-rosa',
      'treeAngico': 'Angico',
      'treeJatoba': 'Jatobá',
      'treeCanelas': 'Canelas',
      'treePerobaRosa': 'Peroba-rosa',
      'treeAroeiraPimenteira': 'Aroeira-pimenteira',
      'treeInga': 'Ingá',
      'treeSapucaia': 'Sapucaia',
    },
    'es': {
      'welcome': '¡Hola, bienvenido/a! 👋',
      'myTrees': 'Tus Árboles',
      'seeAll': 'Ver todos',
      'adoptTree': 'Adoptar un Árbol',
      'reforestation': 'Reforestación local',
      'nativeSpecies': 'Especies nativas del Valle del Sapucaí',
      'ranking': 'posición en el ranking',
      'treesAdopted': 'Árboles adoptados',
      'atlanticForest': 'Mata Atlántica',
      'forest': 'Bosque',
      'map': 'Mapa',
      'incentives': 'Incentivos',
      'settings': 'Configuraciones',
      'loginTitle': 'Bienvenido a EcoMind 🌱',
      'emailOrUser': 'Correo o usuario',
      'password': 'Contraseña',
      'createNewAccount': 'Crear nueva cuenta',
      'enter': 'Entrar',
      'defaultEcoUser': 'Usuario EcoMind',
      'defaultUser': 'Usuario',
      'monthsPlanted': 'meses plantada',
      'endangeredTag': '🔴 Amenazada',
      'perMonth': '/mes',
      'adoptedStatus': '¡✓ Adoptada!',
      'adoptAction': 'Adoptar',

      // Services
      'errGetUser': 'Error al obtener el usuario registrado.',
      'errSaveProfile': 'Cuenta creada en Auth, pero falló al guardar datos del perfil. Inténtalo de nuevo.',
      'errUserNotFound': 'Nombre de usuario no encontrado.',
      'errNoEmailAssociated': 'Ningún correo asociado a este nombre de usuario.',
      'errInvalidCredentials': 'Correo, usuario o contraseña incorrectos.',
      'errInvalidCredentialsDetail': 'Correo o contraseña incorrectos. Verifica tus credenciales.',
      'errEmailNotFound': 'Ningún usuario encontrado para este correo.',
      'errWrongPassword': 'Contraseña incorrecta. Inténtalo de nuevo.',
      'errEmailInUse': 'Este correo ya está en uso por otra cuenta.',
      'errInvalidEmail': 'El correo ingresado no es válido.',
      'errWeakPassword': 'La contraseña debe tener al menos 6 caracteres.',
      'errUserDisabled': 'Esta cuenta de usuario ha sido desactivada.',
      'errTooManyRequests': 'Demasiados intentos fallidos. Inténtalo más tarde.',
      'errNetworkFailed': 'Fallo en la conexión de red. Verifica tu internet.',

      // Leaderboard / Ranking
      'rankingTitle': 'Ranking 🌿',
      'noRankingData': 'No se encontraron datos del ranking.',
      'anonymous': 'Anónimo',
      'treesCountLabel': 'árboles',

      // Map / Mapa
      'mapTitle': 'Mapa de Reforestación 🗺️',
      'mapLoadError': 'Error al cargar el mapa:',
      'mapLocationHeader': 'Santa Rita do Sapucaí - MG',
      'mapTreesMapped': 'árboles mapeados',
      'mapYourTreesCount': 'tuyos',
      'legendMyTrees': 'Tus árboles ⭐',
      'legendCommunity': 'Comunidad 🌳',
      'yourTreeBadge': 'Tu Árbol',
      'biomeLabel': 'Bioma',
      'locationLabel': 'Ubicación',
      'removeTreeBtn': 'Eliminar Árbol',
      'treeRemovedSuccess': '¡fue eliminado con éxito!',
      'treeRemoveError': 'Error al eliminar el árbol:',

      // Profile / Perfil
      'myProfileTitle': 'Mi Perfil',
      'memberSince': 'Miembro desde Agosto, 2026',
      'accountControl': 'Control de la Cuenta',
      'changeUsername': 'Cambiar nombre de usuario',
      'changePassword': 'Cambiar contraseña',
      'logout': 'Cerrar sesión',
      'deleteAccount': 'Eliminar cuenta',
      'deleteAccountTitle': '¿Eliminar Cuenta?',
      'deleteAccountWarning': 'Esta acción es irreversible y borrará todos tus datos y árboles adoptados.',
      'deleteAccountPinPrompt': 'Para confirmar, ingresa el siguiente código:',
      'cancel': 'Cancelar',
      'deletePermanently': 'Eliminar Definitivamente',
      'reauthRequired': 'Por seguridad, vuelve a iniciar sesión antes de eliminar la cuenta.',
      'deleteAccountError': 'Error al eliminar la cuenta:',
      'unexpectedError': 'Error inesperado:',

      // Settings / Configuraciones
      'settingsGeneral': 'General',
      'languageOption': 'Idioma',
      'notificationsOption': 'Notificaciones',
      'settingsSecuritySupport': 'Seguridad y Soporte',
      'privacyOption': 'Privacidad',
      'helpSupportOption': 'Ayuda y Soporte',

      // Home Screen Extras
      'defaultExplorer': 'Explorador',
      'regionTag': '🌱 EcoMind · Sur de Minas',
      'welcomeHome': '¡Hola, bienvenido/a! 👋',
      'bocainaCaptionWeb': 'Serra da Bocaina, en la frontera de los estados de São Paulo y Río de Janeiro',
      'bocainaCaptionMobile': 'Serra da Bocaina, en la frontera de los estados de SP y RJ',
      'atlanticForestTitle': 'Mata Atlántica',
      'atlanticForestBody': 'La Mata Atlántica es el principal bioma de la costa este de Brasil, abarcando principalmente los estados de la región Sudeste y Sur. Aquí se encuentran las cuencas de los principales ríos brasileños y una biodiversidad gigantesca, con miles de especies. En el estado de Minas Gerais se alberga el 70% de los mamíferos de todo el bioma, además de diversos tipos de vegetación. \n\nDesafortunadamente, la Mata Atlántica también es uno de los biomas más amenazados del país, restando solo el 15.3% de su cobertura original en el territorio nacional. En Minas, la situación es aún más crítica, con solo el 7% de la cobertura original preservada. Los principales puntos de reserva son el Valle del Río Doce, Valle del Jequitinhonha y la región sur del estado, cerca de la Serra da Mantiqueira. \n\nEn los años 2021 y 2022, Minas fue el estado que más árboles deforestó del bioma. En un mundo cada vez más amenazado por el cambio climático (como El Niño que alcanzará récords históricos en los próximos meses), es esencial que el ecosistema sea preservado y reforestado.',
      'learnMoreAtlanticForest': 'Más información sobre la Mata Atlántica',
      'sourcesAtlanticForest': 'Fuentes: SOS Mata Atlántica, IBGE, Reserva de la Biosfera de la Mata Atlántica, G1',
      'loginToSeeTrees': 'Inicia sesión para ver tus árboles.',
      'errLoadTrees': 'Error al cargar los árboles:',
      'noTreesFound': 'No se encontraron árboles para esta cuenta.\n¡Haz clic en el círculo 🌱 abajo para registrar el primero!',

      // Incentives Screen
      'incentiveA': 'Beneficio A',
      'incentiveB': 'Beneficio B',
      'incentiveC': 'Beneficio C',
      'incentiveD': 'Beneficio D',
      'partnerMunSantaRita': 'Municipalidad de Santa Rita do Sapucaí',
      'partnerGovMinas': 'Gobierno del Estado de Minas Gerais',
      'partnerGovFederal': 'Gobierno Federal',
      'categoryFiscal': 'Beneficio Fiscal',
      'noDescriptionYet': 'Aún no hay una descripción.',
      'allFilter': 'Todos',
      'taxesFilter': '📜 Impuestos',
      'incentivesAndRewards': 'Incentivos y Recompensas',
      'incentivesSubtitle': 'Adopta árboles y desbloquea beneficios exclusivos',
      'unlockedStatus': '¡Desbloqueado! 🎉',
      'goalReached': '¡Objetivo alcanzado!',
      'treesProgressLabel': 'de',

      // Account Screen / Criar Conta
      'createAccountTitle': 'Crear Nueva Cuenta 🌱',
      'usernameHint': 'Nombre de usuario',
      'emailHint': 'Correo electrónico',
      'passwordHint': 'Contraseña',
      'confirmPasswordHint': 'Confirmar contraseña',
      'registerBtn': 'Registrarse',
      'accountCreatedSuccess': '¡Cuenta creada con éxito! 🌱',
      'errEmptyUser': 'Por favor, ingresa un nombre de usuario.',
      'errEmptyEmail': 'Por favor, ingresa un correo electrónico.',
      'errInvalidEmailFormat': 'Ingresa un correo electrónico válido.',
      'errEmptyPassword': 'Por favor, ingresa una contraseña.',
      'errPasswordTooShort': 'La contraseña debe tener al menos 6 caracteres.',
      'errEmptyConfirmPassword': 'Por favor, confirma tu contraseña.',
      'errPasswordsDoNotMatch': 'Las contraseñas no coinciden.',

      // Adopt Screen / Adotar Árvores
      'adoptTreeTitle': 'Adoptar Árbol',
      'adoptSubtitle': 'Especies nativas del Valle del Sapucaí · Sur de Minas',
      'confirmAdoptionTitle': 'Confirmar Adopción 🌿',
      'speciesLabel': 'Especie',
      'monthlyPriceLabel': 'Valor mensual: R\$',
      'paymentMethodLabel': 'Método de Pago:',
      'pixPayment': 'PIX (Aprobación Instantánea)',
      'cardPayment': 'Tarjeta de Crédito Simulada',
      'payAndAdoptBtn': 'Pagar y Adoptar',
      'loginRequiredToAdopt': '⚠️ Debes iniciar sesión para adoptar un árbol.',
      'adoptionSuccessMsg': '🌱 ¡Pago confirmado! {treeName} fue adoptada con éxito.',
      'adoptionErrorMsg': 'Error al procesar la adopción. Inténtalo de nuevo.',
      'locationValeSapucai': 'Valle del Sapucaí · MG',

      // Filtros de Adotar Árvores
      'filterAll': 'Todas',
      'filterEndangered': '🔴 Amenazadas',
      'filterRiparianForest': '🏞️ Bosque ribereño',
      'filterFlowering': '🌼 Floración',
      'filterAttractsBirds': '🐦 Atrae aves',
      'filterFeedsFauna': '🐆 Alimenta a la fauna',
      'filterLargeSize': '🌳 Gran tamaño',
      'filterRecoversSoil': '🌱 Recupera el suelo',
      'filterWindDispersal': '💨 Dispersión por el viento',
      'filterNitrogenFixation': '🍃 Fijación de nitrógeno',
      'filterEdibleNuts': '🌰 Nueces comestibles',
      'filterEdibleFruits': '🥭 Frutas comestibles',

      // Biomas e Locais
      'biomeAtlanticForest': 'Mata Atlántica',

      // Espécies e Nomes de Árvores
      'treeIpeAmarelo': 'Guayacán Amarillo',
      'treeJacaranda': 'Jacarandá',
      'treeCedroRosa': 'Cedro Rosado',
      'treeJequitibaRosa': 'Jequitibá Rosado',
      'treeAngico': 'Angico',
      'treeJatoba': 'Algarrobo / Jatobá',
      'treeCanelas': 'Canelas',
      'treePerobaRosa': 'Peroba Rosa',
      'treeAroeiraPimenteira': 'Pimentero Brasileño',
      'treeInga': 'Pacay / Ingá',
      'treeSapucaia': 'Sapucaia',
    },
  };

  /// Busca a tradução baseada no idioma do celular. Se não for 'es', usa 'pt' como padrão.
  static String get(BuildContext context, String key) {
    String langCode = currentLocale.value.languageCode;
    if (!_localizedValues.containsKey(langCode)) {
      langCode = 'pt';
    }
    return _localizedValues[langCode]?[key] ?? key;
  }

  static void changeLanguage(String langCode) {
    currentLocale.value = Locale(langCode);
  }
}