// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFPayWe3us77DRJZZIvB65Wxe4VdRHmDw',
    appId: '1:53995905318:web:598026b29c6b3c5ce6a1e7',
    messagingSenderId: '53995905318',
    projectId: 'ecomind-4fe6a',
    authDomain: 'ecomind-4fe6a.firebaseapp.com',
    storageBucket: 'ecomind-4fe6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGNi8f0hL4F5F4ZmtmhG9F4rgCqRUe2CU',
    appId: '1:53995905318:android:acb6b3827f6dd3bfe6a1e7',
    messagingSenderId: '53995905318',
    projectId: 'ecomind-4fe6a',
    storageBucket: 'ecomind-4fe6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkN-5HME00qV82jT7QoPETzAM_betHeY',
    appId: '1:53995905318:ios:2c2cb9578744bc27e6a1e7',
    messagingSenderId: '53995905318',
    projectId: 'ecomind-4fe6a',
    storageBucket: 'ecomind-4fe6a.firebasestorage.app',
    iosBundleId: 'com.example.raizes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhkN-5HME00qV82jT7QoPETzAM_betHeY',
    appId: '1:53995905318:ios:2c2cb9578744bc27e6a1e7',
    messagingSenderId: '53995905318',
    projectId: 'ecomind-4fe6a',
    storageBucket: 'ecomind-4fe6a.firebasestorage.app',
    iosBundleId: 'com.example.raizes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFPayWe3us77DRJZZIvB65Wxe4VdRHmDw',
    appId: '1:53995905318:web:b7e189d998224db3e6a1e7',
    messagingSenderId: '53995905318',
    projectId: 'ecomind-4fe6a',
    authDomain: 'ecomind-4fe6a.firebaseapp.com',
    storageBucket: 'ecomind-4fe6a.firebasestorage.app',
  );
}
